name: ${name}
version: ${version}
main: ${main}
api-version: 1.20
description: A Minecraft challenge plugin with hardcore Ender Dragon fights
author: li.angu
commands:
  create:
    description: Create a new challenge
    usage: /create [name]
  list:
    description: List all available challenges
    usage: /list
  join:
    description: Join an existing challenge
    usage: /join <challenge-id>
  leave:
    description: Leave your current challenge
    usage: /leave
  info:
    description: Show information about a challenge
    usage: /info [challenge-id]
  delete:
    description: Delete a challenge and its worlds
    usage: /delete <challenge-id> [confirm]
    permission: challengeplugin.delete
  challenge:
    description: Open the challenge menu
    usage: /challenge
  lang:
    description: Change your preferred language
    usage: /lang <language>
  debugdragon:
    description: Debug command for the Ender Dragon
    usage: /debugdragon
    permission: challengeplugin.debug
  debugcolors:
    description: Display all Minecraft chat colors and formats
    usage: /debugcolors
    permission: challengeplugin.debug
  debugrespawn:
    description: Teleport yourself or all players to their spawn points
    usage: /debugrespawn [all]
    permission: challengeplugin.debug
permissions:
  challengeplugin.debug:
    description: Access to debug commands
    default: op
  challengeplugin.delete:
    description: Permission to delete challenges
    default: op
