name: ${name}
version: ${version}
main: ${main}
api-version: 1.20
description: A Minecraft challenge plugin with hardcore Ender Dragon fights
author: li.angu
commands:
  challenge:
    description: Manage minecraft challenges
    usage: /challenge <create|list|join|leave|info>
    permission: challengeplugin.command.challenge
  lang:
    description: Change your preferred language
    usage: /lang <language>
    permission: challengeplugin.command.language