name: ${name}
version: ${version}
main: ${main}
api-version: 1.20
description: A Minecraft challenge plugin with hardcore Ender Dragon fights
author: li.angu
commands:
  challenge:
    description: Manage minecraft challenges
    usage: /challenge <create|list|join|leave|info>
  lang:
    description: Change your preferred language
    usage: /lang <language>
  debugdragon:
    description: Debug command for the Ender Dragon
    usage: /debugdragon
    permission: challengeplugin.debug
  debugcolors:
    description: Display all Minecraft chat colors and formats
    usage: /debugcolors
    permission: challengeplugin.debug
