name: Build and Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Get short SHA
      id: shortsha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs

    - name: Create Release (Tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        generate_release_notes: true
        
    - name: Create Snapshot Release
      if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
        name: SNAPSHOT-${{ steps.shortsha.outputs.sha }}
        tag_name: snapshot-${{ steps.shortsha.outputs.sha }}
        prerelease: true
        generate_release_notes: true
